name = "amqp"
version = "0.3.1"
description = "AMQP 0-9-1 client library for Ada"
tags = ["amqp", "messaging", "rabbitmq", "protocol"]
website = "https://github.com/geewiz/amqp_ada"
licenses = "Apache-2.0"
authors = ["Jochen Lillich <contact@geewiz.dev>"]
maintainers = ["Jochen Lillich <contact@geewiz.dev>"]
maintainers-logins = ["geewiz"]
