name = "amqp_examples"
version = "0.2.0"
description = "Example programs for the AMQP Ada library"
website = "https://github.com/geewiz/amqp_ada"
authors = ["Jochen Lillich"]
maintainers = ["jochen@lillich.co"]
maintainers-logins = ["geewiz"]
licenses = "Apache-2.0"
tags = ["amqp", "examples", "messaging", "rabbitmq"]

project-files = ["examples.gpr"]

[[depends-on]]
amqp = "~0.2"

[gpr-externals]

[gpr-set-externals]

[available.'case(os)']
linux = true
macos = true
windows = true
